version: "3.8"
services:
  server:
    env_file: .env.prod
    build: .
    ports:
      - "3030:3030"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    env_file: .env.prod
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db-data:
